### ISSUE TITLE
TypeError: bad operand type for unary -: 'TopKV2'     

### ISSUE THREAD

**Issue by longmalongma** [for-ai/TD#6] opened 2019-05-30 23:43 UTC
Thank you for your reply.I successfully put your code in my model,but when I call the function of targeted dropout,I meet a problem, the problem is:
TypeError: bad operand type for unary -: 'TopKV2'     
can you help me solve this problem?my these code is that:

![image](https://user-images.githubusercontent.com/40291722/58672005-76dc3280-8377-11e9-8233-8dfbcc44cff4.png)
![image](https://user-images.githubusercontent.com/40291722/58672035-a2f7b380-8377-11e9-8726-1d5fbde3891c.png)

**Comment by aidangomez** [comment] 2019-05-31 11:02
Duplicate of #5

**Closed as completed by aidangomez** 2019-05-31 11:02 UTC
